Fixed error if the current beta is deleted while updating Xcode
If the current beta (for example, Xcode 14.3.1 Release Candidate) is deleted while updating the next beta (for example, Xcode 14.3.1), we get the following error:

```
- /Applications/Xcode-beta.app will stop linking to <XCODES_DIRECTORY>/Xcode-14.3.1-Release.Candidate.app and start pointing to Xcode 14.3.1 (14E300c).
Traceback (most recent call last):
  File "<bin_path>/xcode-update", line 262, in <module>
    sys.exit(main())
  File "<bin_path>/xcode-update", line 54, in main
    update_links(dry_run=True)
  File "<bin_path>/xcode-update", line 133, in update_links
    if is_release_version(current_beta):
  File "<bin_path>/xcode-update", line 185, in is_release_version
    raise AssertionError(f"{path} doesn't seems to be a valid Xcode version")
AssertionError: <XCODES_DIRECTORY>/Xcode-14.3.1-Release.Candidate.app doesn't seems to be a valid Xcode version
```

Fixed this by checking that the current beta that'll be tried to be used as the release version wasn't deleted.

- This isn't the most elegant solution, but it should work.
- Also removed a superfluous `if path is None` check that could hide errors like this in the future.